{% set name = "buildbot" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7e9412f354fa143711fa5f4b60c703801bd2bb925f3c8393990da551af3b2452

build:
  number: 0
  noarch: python
  entry_points:
    - buildbot=buildbot.scripts.runner:run
    - buildbot_windows_service=buildbot.scripts.windows_service:HandleCommandLine
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=8.0
  run:
    - autobahn >=0.16.0
    - jinja2 >=2.1
    - pyjwt
    - python >=3.6
    - python-dateutil >=1.5
    - pyyaml
    - setuptools >=8.0
    - sqlalchemy >=1.2.0
    - sqlalchemy-migrate >=0.13
    - twisted >=17.9.0
    - txaio >=2.2.2
    - zope.interface >=4.1.1

test:
  imports:
    - buildbot
    - buildbot.changes
  commands:
    - pip check
    - buildbot --help
    - buildbot_windows_service --help  # [win]
  requires:
    - pip

about:
  home: https://buildbot.net/
  license: GPL-2.0
  license_file: COPYING
  summary: Python-based continuous integration testing framework
  doc_url: https://docs.buildbot.net

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
    - marcelotrevisani
