travis:
  secure:
    BINSTAR_TOKEN: HM+X6UeycSdNmqXxKRAdDIIcOkMuiRCrxiuv10ouvgiuODOxf3Moht66mco1v099oNiUjMJ0et0gnn4IK6RFrdk/JLUUBUPI+K7yaiqQNOhwOVM9VdsvIWQOW2hfI8OBdk2oSG9KY+UAnLKJu0QagCZDY5iXVfbcw6XVSjWtsg9Rv0RcNNe2MEcsFdMMXJgz345+a5HzPjoTLTMMOl29En+UUS+LSijm/EZGo1oJh60xD7zWl/SOny6T0jc1WgA9NHawKsv3Zz6ODJEaXwX9Ya/vA5AVl5jxhMt2hAIv0fi9+dwe9VpiDqmEUk07t/LulMxlcqpqfT+8/mir/N4FjhNhxmUNA2yiO6W/8ra8hSHocJlNrpYirW4e9rLJKK4YOCbKrZeaEALupq8/s1qU6950r8EulYFc3B3jKQKPnXXzkvKZIyyohIQGEE5nmJeRduGYBS+5blC9M9Oi15U39E7F9sa9YrO2QGZyVPOA22ccBX1AI4lUxwoDErCGHM0rBDQmzaAtLmTeAijKKuiVw3qJlhueDG3e69ak4tqzVkd9+AHxlUGBFzGYFb7skeyzM02zKxdjteWsDzChw3LqpKUYJko2gllASVApeAexGGsjtUZ5Z80k4vVQbD8UXW7GE0rMQ5a1pm8yrDl0tCL+ztZUH9uaiJ3qiaGdeUBmqSM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
bot:
  automerge: true
